version: 2
jobs:
  build:
    working_directory: /jsondb
    docker:
      - image: node:6.10.0
    steps:
      # Ensure your image has git, otherwise the checkout step will fail
      - run: apt-get -qq update; apt-get -y install git

      # Checkout timing is no longer hardcoded, so this step can occur anywhere
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install Dependencies
          command: npm install

     # Caching is fully customizable in 2.0
     - save_cache:
         key: dependency-cache-{{ checksum "package.json" }}
         paths:
           - .node_modules

      # Again, no inference in 2.0 yet, so nothing to override here, either.
      # Just use any test commands.
      - run:
          name: Run Tests
          command: npm test

      - store_artifacts:
          path: test-results.xml
          destination: tests

      - store_artifacts:
          path: coverage
          destination: coverage

      - store_test_results:
          path: test-results.xml
